namespace Infinium.Domain.Contracts;

public sealed record TypedOutputCountsContract(
    long Observations,
    long DeterministicResults,
    long ExternalClaims,
    long ApplicationLinks,
    long DiscoveryLeads,
    long ModelProposals,
    long ProposalAdmissions,
    long Candidates,
    long Hypotheses,
    long Findings,
    long Recommendations,
    long SupportedCases,
    long LeadOnlyCases,
    long Abstentions,
    long InvalidInputs,
    long CoverageGaps,
    long Failures,
    long DocumentationRevisions,
    long Passages,
    long CandidateDecisions,
    long ReconciliationAssessments,
    long LineageEvents);

public sealed record CoverageStateCountsContract(
    long Completed,
    long CompletedWithGaps,
    long Failed,
    long SkippedByConfiguration,
    long SkippedByLimit,
    long Unsupported);

public sealed record CliCostContract(
    long ProviderInputTokens,
    long ProviderOutputTokens,
    long ProviderReasoningTokens,
    long DispatchCount,
    long ToolCallCount,
    long? CalculatedActualNanoUsd,
    long ReservedNanoUsd,
    bool UnresolvedHold);

public sealed record CliSummaryAggregateContract(
    string SchemaId,
    ContractVersion SchemaVersion,
    OpaqueId RunId,
    CliOutcome Outcome,
    CliExitCode ExitCode,
    TypedOutputCountsContract TypedCounts,
    CoverageStateCountsContract CoverageStateCounts,
    long DurationMs,
    CliCostContract Cost,
    ReadinessScope ReadinessScope,
    bool NoSafetyGuarantee);

public sealed record RunOutputAggregateContract(
    OpaqueId RunId,
    OpaqueId SnapshotId,
    OpaqueId AnalysisContextId,
    OpaqueId EffectiveScanConfigurationId,
    OpaqueId ResolvedInputManifestId,
    Sha256Fingerprint CliSummaryFingerprint,
    IReadOnlyList<ObservationContract> Observations,
    IReadOnlyList<DeterministicResultContract> DeterministicResults,
    IReadOnlyList<ExternalClaimContract> ExternalClaims,
    IReadOnlyList<ExternalClaimApplicationLinkContract> ExternalClaimApplicationLinks,
    IReadOnlyList<DiscoveryLeadContract> DiscoveryLeads,
    IReadOnlyList<ModelProposalContract> ModelProposals,
    IReadOnlyList<ProposalAdmissionContract> ProposalAdmissions,
    IReadOnlyList<CandidateContract> Candidates,
    IReadOnlyList<HypothesisContract> Hypotheses,
    IReadOnlyList<FindingOccurrenceContract> Findings,
    IReadOnlyList<RecommendationContract> Recommendations,
    IReadOnlyList<CaseOccurrenceContract> SupportedCases,
    IReadOnlyList<CaseOccurrenceContract> LeadOnlyCases,
    IReadOnlyList<AbstentionContract> Abstentions,
    IReadOnlyList<InvalidInputContract> InvalidInputs,
    IReadOnlyList<CoverageGapContract> CoverageGaps,
    IReadOnlyList<FailureContract> Failures,
    IReadOnlyList<TypedCollectionStateContract> CollectionStates,
    IReadOnlyList<TaxonomyAssignmentContract> TaxonomyAssignments,
    IReadOnlyList<CoverageContract> Coverage,
    IReadOnlyList<AnalyzerDeclarationContract> AnalyzerDeclarations,
    ReadinessPlaceholderContract Readiness,
    ReplayabilityAssessmentContract Replayability,
    AuditabilityAssessmentContract Auditability,
    bool PotentiallySensitive,
    IReadOnlyList<string> UnsupportedCapabilities);
