namespace Infinium.Domain.Contracts;

public enum ProviderAvailabilityState
{
    Unspecified,
    Available,
    Unavailable,
    Unsupported,
    NotApplicable,
    NotUsed,
}

public enum ProviderProfileState
{
    Unspecified,
    PendingEnrollment,
    ActiveUnverified,
    ActiveVerified,
    Replacing,
    Disabled,
    DeletePending,
    Deleted,
    SecureStoreUnavailable,
    RecoveryRequired,
}

public enum ProviderOperationState
{
    Unspecified,
    Proposed,
    Confirmed,
    Reserved,
    Assigned,
    InputBoundBlocked,
    FinalGateAuthorized,
    TransportNotStarted,
    TransportMayHaveStarted,
    ResponseStaged,
    Admitted,
    Rejected,
    Settled,
    UnresolvedHold,
}

public enum ProviderResponseState
{
    Unspecified,
    Completed,
    Refusal,
    Incomplete,
    Failed,
    Queued,
    InProgress,
    Malformed,
    Oversized,
    Mismatched,
    Unknown,
    Cancelled,
}

public enum ProviderOperationKind
{
    Unspecified,
    TransportQualification,
    SourceClaimExtraction,
    CandidateInvestigation,
}

public enum ProposalAdmissionState
{
    Unspecified,
    Proposed,
    Admitted,
    Rejected,
    Abstained,
    Unavailable,
    Unsupported,
    Deleted,
}

public enum ProviderInputBoundProofState
{
    Unspecified,
    AuthorityRequired,
    Proved,
}

public sealed record ProviderInputBoundProofContract(
    string PolicyId,
    string PolicyVersion,
    ProviderInputBoundProofState Status);

public sealed record ProviderIdentityReferenceContract(
    OpaqueId Identity,
    Sha256Fingerprint Fingerprint);

public sealed record ProviderFiniteLimitsContract(
    long MaximumRequestBytes,
    long MaximumInputTokens,
    long MaximumOutputTokens,
    long MaximumRawResponseBytes,
    long MaximumDispatchCount,
    long MaximumCalculatedNanoUsd,
    long DeadlineMilliseconds);

public sealed record ProviderPriceRuleContract(
    OpaqueId RuleId,
    string Provider,
    string Model,
    string ServiceTier,
    string ContextBand,
    string CacheClass,
    string TokenClass,
    string ToolClass,
    string Region,
    string Currency,
    long NumeratorNanoUsd,
    long DenominatorTokens,
    string Revision);

public sealed record ProviderCapabilitySnapshotContract(
    OpaqueId Identity,
    Sha256Fingerprint Fingerprint,
    string Provider,
    string Model,
    string ServiceTier,
    string ReasoningEffort,
    string ReasoningContext,
    string ReasoningMode,
    bool Store,
    bool Background,
    bool Stream,
    string ToolChoice,
    int ToolCount,
    string Truncation,
    string PromptCacheMode,
    bool HasPromptCacheKey,
    bool HasPromptCacheBreakpoint,
    long MaximumContextTokens,
    string Revision);

public sealed record ProviderPriceSnapshotContract(
    OpaqueId Identity,
    Sha256Fingerprint Fingerprint,
    string Provider,
    string Model,
    string ServiceTier,
    string Currency,
    string Revision,
    IReadOnlyList<ProviderPriceRuleContract> Rules);

public sealed record ProviderQuantityContract(
    ProviderAvailabilityState Availability,
    long? Value);

public sealed record ProviderUsageContract(
    ProviderAvailabilityState Availability,
    ProviderQuantityContract DispatchCount,
    ProviderQuantityContract InputTokens,
    ProviderQuantityContract OutputTokens,
    ProviderQuantityContract TotalTokens,
    ProviderQuantityContract ReasoningTokens,
    ProviderQuantityContract CacheReadTokens,
    ProviderQuantityContract CacheWriteTokens,
    ProviderQuantityContract PricedToolCalls,
    ProviderQuantityContract CalculatedNanoUsd,
    ProviderAvailabilityState BillingAvailability,
    ProviderAvailabilityState RateAvailability,
    ProviderAvailabilityState CreditAvailability,
    UsageReceiptState ReceiptState);

public sealed record ProviderRateLimitFactContract(
    string Scope,
    string Dimension,
    ProviderAvailabilityState Availability,
    long? Limit,
    long? Remaining,
    UtcTimestamp ObservedAt,
    UtcTimestamp? ResetsAt);

public sealed record ProviderAccessProfileDocument(
    string SchemaId,
    string SchemaVersion,
    OpaqueId ProfileId,
    OpaqueId GenerationId,
    long GenerationOrdinal,
    long RevocationEpoch,
    string Provider,
    string Purpose,
    string DisplayLabel,
    ProviderProfileState LifecycleState,
    ProviderAvailabilityState VerificationState,
    OpaqueId? AccountIdentityId,
    OpaqueId? BillingScopeIdentityId,
    OpaqueId? CapabilitySnapshotId,
    OpaqueId? IntentId,
    string RecoveryDisposition,
    string CleanupDisposition,
    UtcTimestamp RecordedAt);

public sealed record ProviderOperationDocument(
    string SchemaId,
    string SchemaVersion,
    OpaqueId OperationId,
    OpaqueId OwnerId,
    string OwnerKind,
    ProviderOperationKind OperationKind,
    OpaqueId JobNodeId,
    OpaqueId CommandId,
    OpaqueId InstallationSnapshotId,
    OpaqueId AnalysisContextId,
    OpaqueId EffectiveConfigurationId,
    OpaqueId ResolvedInputManifestId,
    OpaqueId ProfileId,
    OpaqueId GenerationId,
    long RevocationEpoch,
    ProviderCapabilitySnapshotContract CapabilitySnapshot,
    ProviderPriceSnapshotContract PriceSnapshot,
    OpaqueId PromptId,
    Sha256Fingerprint PromptFingerprint,
    OpaqueId OutputSchemaId,
    Sha256Fingerprint OutputSchemaFingerprint,
    Sha256Fingerprint RequestFingerprint,
    ProviderIdentityReferenceContract CanonicalRequestPayload,
    long CanonicalRequestBytes,
    Sha256Fingerprint SettingsFingerprint,
    ProviderInputBoundProofContract InputBoundProof,
    ProviderFiniteLimitsContract Limits,
    ProviderOperationState State,
    string TransportState,
    string ReceiptState,
    ProviderUsageContract Usage,
    string SettlementState,
    string ReplayState,
    UtcTimestamp RequestedAt,
    UtcTimestamp ConfirmedAt,
    UtcTimestamp DispatchDeadline,
    long CoordinatorFencingEpoch,
    UtcTimestamp RecordedAt,
    OpaqueId? AuthorizationId = null,
    OpaqueId? AttemptId = null,
    OpaqueId? RequestId = null,
    OpaqueId? ReservationId = null,
    OpaqueId? DispatchFenceId = null,
    OpaqueId? TransportEventId = null,
    OpaqueId? ReceiptId = null,
    OpaqueId? ResponseId = null,
    OpaqueId? UsageEntryId = null,
    OpaqueId? SettlementId = null,
    OpaqueId? ReplayEdgeId = null);

public sealed record ProviderResponseDocument(
    string SchemaId,
    string SchemaVersion,
    OpaqueId ResponseRecordId,
    OpaqueId OperationId,
    string OwnerKind,
    OpaqueId OwnerId,
    OpaqueId? AuthorizationId,
    OpaqueId? AttemptId,
    OpaqueId? RequestId,
    OpaqueId? ReservationId,
    OpaqueId? DispatchFenceId,
    ProviderOperationKind OperationKind,
    ProviderFiniteLimitsContract Limits,
    ProviderInputBoundProofContract InputBoundProof,
    ProviderAvailabilityState Availability,
    ProviderAvailabilityState RawResponseAvailability,
    ProviderIdentityReferenceContract? RawResponsePayload,
    long? RawResponseBytes,
    long MaximumRawResponseBytes,
    long? OverflowObservedExcessBytes,
    ProviderIdentityReferenceContract? ResponseHeadersPayload,
    long? ResponseHeadersBytes,
    ProviderAvailabilityState ResponseHeadersAvailability,
    int? HttpStatus,
    ProviderAvailabilityState HttpStatusAvailability,
    string? ProviderResponseId,
    ProviderAvailabilityState ProviderResponseIdAvailability,
    string? ClientRequestId,
    ProviderAvailabilityState ClientRequestIdAvailability,
    string? ProviderRequestId,
    ProviderAvailabilityState ProviderRequestIdAvailability,
    ProviderResponseState State,
    string? RefusalCode,
    ProviderAvailabilityState RefusalAvailability,
    string? IncompleteReason,
    ProviderAvailabilityState IncompleteAvailability,
    string? ErrorCode,
    ProviderAvailabilityState ErrorAvailability,
    string RequestedModel,
    string? ReturnedModel,
    ProviderAvailabilityState ReturnedModelAvailability,
    string RequestedServiceTier,
    string? ReturnedServiceTier,
    ProviderAvailabilityState ReturnedServiceTierAvailability,
    string ReasoningContext,
    string ReasoningMode,
    string PromptCacheMode,
    ProviderUsageContract Usage,
    IReadOnlyList<ProviderRateLimitFactContract> RateLimitFacts,
    ProviderIdentityReferenceContract? BillingEvidencePayload,
    ProviderAvailabilityState BillingEvidenceAvailability,
    ProposalAdmissionState ValidationState,
    ProposalAdmissionState AdmissionState,
    UtcTimestamp RecordedAt);

public sealed record ProviderSemanticAdmissionLinkContract(
    OpaqueId AdmissionId,
    OpaqueId ProposalId,
    OpaqueId AuthorizationId,
    OpaqueId OperationId,
    OpaqueId ResponseRecordId,
    string OwnerKind,
    OpaqueId OwnerId,
    OpaqueId RootSubjectId,
    OpaqueId ValidationId,
    OpaqueId ApplicationLinkId,
    ProposalAdmissionState State);

public sealed record SourceClaimAdmissionCorrelationContract(
    OpaqueId AdmissionId,
    OpaqueId ProposalId,
    OpaqueId AuthorizationId,
    OpaqueId OperationId,
    OpaqueId ResponseRecordId,
    string OwnerKind,
    OpaqueId OwnerId,
    OpaqueId RootSubjectId,
    OpaqueId ValidationId,
    OpaqueId AdmissionCorrelationId,
    ProposalAdmissionState State);

public sealed record CitationProposalContract(
    OpaqueId ProposalId,
    OpaqueId PassageId,
    string Claim,
    IReadOnlyList<OpaqueId> ConditionIds,
    ProposalAdmissionState State,
    string Reason);

public sealed record SourceClaimExtractionDocument(
    string SchemaId,
    string SchemaVersion,
    OpaqueId AcquisitionRunId,
    OpaqueId OperationId,
    string OwnerKind,
    OpaqueId OwnerId,
    OpaqueId ParentAnalysisRunId,
    OpaqueId ApplicationScopeId,
    OpaqueId CostAttributionScopeId,
    OpaqueId SourceRevisionId,
    IReadOnlyList<OpaqueId> PassageIds,
    string DeclaredPurpose,
    IReadOnlyList<CitationProposalContract> ClaimProposals,
    IReadOnlyList<OpaqueId> ContradictionEvidenceIds,
    IReadOnlyList<string> Abstentions,
    IReadOnlyList<string> Gaps,
    IReadOnlyList<OpaqueId> ValidationIds,
    IReadOnlyList<OpaqueId> AdmissionCorrelationIds,
    IReadOnlyList<SourceClaimAdmissionCorrelationContract> AdmissionCorrelations);

public sealed record HypothesisProposalContract(
    OpaqueId ProposalId,
    OpaqueId CandidateId,
    string Hypothesis,
    IReadOnlyList<OpaqueId> SupportingEvidenceIds,
    IReadOnlyList<OpaqueId> ContradictingEvidenceIds,
    IReadOnlyList<string> MissingInformation,
    ProposalAdmissionState State,
    string Reason);

public sealed record CandidateInvestigationDocument(
    string SchemaId,
    string SchemaVersion,
    OpaqueId OperationId,
    string OwnerKind,
    OpaqueId OwnerId,
    OpaqueId AnalysisRunId,
    OpaqueId CandidateId,
    IReadOnlyList<OpaqueId> ParticipantIds,
    IReadOnlyList<string> ParticipantRoles,
    IReadOnlyList<OpaqueId> CausalPathIds,
    OpaqueId DependencyClosureId,
    IReadOnlyList<OpaqueId> EvidenceIds,
    IReadOnlyList<HypothesisProposalContract> HypothesisProposals,
    IReadOnlyList<string> Abstentions,
    IReadOnlyList<string> Gaps,
    IReadOnlyList<OpaqueId> ValidationIds,
    IReadOnlyList<OpaqueId> AdmissionLinkIds,
    IReadOnlyList<ProviderSemanticAdmissionLinkContract> AdmissionLinks);

public sealed record ProviderExecutionInputDocument(
    string SchemaId,
    string SchemaVersion,
    OpaqueId OperationId,
    string OwnerKind,
    OpaqueId OwnerId,
    OpaqueId JobNodeId,
    OpaqueId CommandId,
    OpaqueId InstallationSnapshotId,
    OpaqueId AnalysisContextId,
    OpaqueId EffectiveConfigurationId,
    OpaqueId ResolvedInputManifestId,
    OpaqueId ProfileId,
    OpaqueId GenerationId,
    ProviderCapabilitySnapshotContract CapabilitySnapshot,
    ProviderPriceSnapshotContract PriceSnapshot,
    ProviderFiniteLimitsContract Limits,
    OpaqueId PromptId,
    Sha256Fingerprint PromptFingerprint,
    OpaqueId OutputSchemaId,
    Sha256Fingerprint OutputSchemaFingerprint,
    ProviderOperationKind OperationKind,
    Sha256Fingerprint CanonicalRequestFingerprint,
    ProviderInputBoundProofContract InputBoundProof,
    string DispatchAdmission);

public sealed record EffectiveScanConfigurationV2Document(
    string SchemaId,
    string SchemaVersion,
    OpaqueId ConfigurationId,
    OpaqueId LocalConfigurationV1Id,
    Sha256Fingerprint LocalConfigurationV1Fingerprint,
    string LocalConfigurationV1Provenance,
    OpaqueId AccessProfileId,
    OpaqueId GenerationId,
    string Model,
    string ReasoningEffort,
    string ReasoningContext,
    string ReasoningMode,
    bool Store,
    string ServiceTier,
    bool Background,
    bool Stream,
    string ToolChoice,
    int ToolCount,
    string Truncation,
    string PromptCacheMode,
    bool HasPromptCacheKey,
    bool HasPromptCacheBreakpoint,
    ProviderFiniteLimitsContract Limits,
    IReadOnlyList<string> NotUsedBoundaries);

public sealed record ProviderPublicationReferenceContract(
    OpaqueId? OperationId,
    ProviderOperationKind? OperationKind,
    OpaqueId? AcquisitionRunId,
    OpaqueId? AuthorizationId,
    OpaqueId? ResponseId,
    OpaqueId? AdmissionId,
    OpaqueId? UsageEntryId,
    OpaqueId? SettlementId,
    OpaqueId? ReplayEdgeId,
    string Availability,
    bool Live,
    string? AcceptedInputBoundPolicyId = null,
    string? AcceptedInputBoundPolicyVersion = null,
    OpaqueId? LiveAuthorizationId = null);

public sealed record RunOutputV2Document(
    string SchemaId,
    string SchemaVersion,
    OpaqueId RunId,
    ProviderIdentityReferenceContract LocalRunOutputV1,
    OpaqueId EffectiveConfigurationV2Id,
    IReadOnlyList<ProviderPublicationReferenceContract> ProviderOperations,
    IReadOnlyList<OpaqueId> EvidenceAcquisitionRunIds,
    IReadOnlyList<OpaqueId> CapabilityDriftIds,
    IReadOnlyList<OpaqueId> PriceDriftIds,
    IReadOnlyList<string> ProviderGaps,
    bool ContainsRawTransport,
    bool ContainsSecret);

public sealed record CliSummaryV2Document(
    string SchemaId,
    string SchemaVersion,
    OpaqueId RunId,
    Sha256Fingerprint LocalCliSummaryV1Fingerprint,
    string ProviderState,
    ProviderQuantityContract DispatchCount,
    ProviderQuantityContract InputTokens,
    ProviderQuantityContract OutputTokens,
    ProviderQuantityContract ReasoningTokens,
    ProviderQuantityContract CacheReadTokens,
    ProviderQuantityContract CacheWriteTokens,
    ProviderQuantityContract CalculatedNanoUsd,
    ProviderQuantityContract ReservedNanoUsd,
    bool UnresolvedHold,
    string ReplayState,
    IReadOnlyList<string> Gaps,
    bool ContainsRawTransport,
    bool ContainsSecret,
    string? AcceptedInputBoundPolicyId = null,
    string? AcceptedInputBoundPolicyVersion = null,
    OpaqueId? LiveAuthorizationId = null);
