// <auto-generated />
#nullable enable
using System.Text.Json;
using Infinium.Contracts.Protobuf.Application.V1;

namespace Infinium.Application.Runtime;

public sealed record GeneratedRendererMessage(string Operation, string NativeTarget, string MessageKind, string Direction, string PayloadShape, string SchemaDefinition);

public static class GeneratedRendererOperationCatalog
{
    public const string RegistryVersion = "1.3.0";
    public const string RendererContractVersion = "1.4.0";
    public const string RegistrySha256 = "411a9c05604c7664773aa62c36f62817273ecaff228f20e074063bed1414cfa9";
    public static IReadOnlyList<GeneratedRendererMessage> Messages { get; } =
    [
        new("transport.session.establish", "DesktopHost.EstablishRendererSession", "event", "host-to-renderer", "session-initialization-event", "sessionInitializationEvent"),
        new("transport.session.establish", "DesktopHost.EstablishRendererSession", "request", "renderer-to-host", "session-acknowledgement-request", "sessionAcknowledgementRequest"),
        new("transport.gesture.grant", "DesktopHost.GrantRendererGesture", "event", "host-to-renderer", "gesture-grant-event", "gestureGrantEvent"),
        new("application.bootstrap", "ApplicationService.GetApplicationBootstrap", "request", "renderer-to-host", "bootstrap-request", "bootstrapRequest"),
        new("application.bootstrap", "ApplicationService.GetApplicationBootstrap", "response", "host-to-renderer", "bootstrap-response", "bootstrapResponse"),
        new("results.list", "ApplicationService.ListResultItems", "request", "renderer-to-host", "result-list-request", "resultListRequest"),
        new("results.list", "ApplicationService.ListResultItems", "response", "host-to-renderer", "result-list-response", "resultListResponse"),
        new("results.detail", "ApplicationService.GetResultDetail", "request", "renderer-to-host", "result-detail-request", "resultDetailRequest"),
        new("results.detail", "ApplicationService.GetResultDetail", "response", "host-to-renderer", "result-detail-response", "resultDetailResponse"),
        new("progress.read", "ApplicationService.GetProgress", "request", "renderer-to-host", "progress-request", "progressRequest"),
        new("progress.read", "ApplicationService.GetProgress", "response", "host-to-renderer", "progress-response", "progressResponse"),
        new("progress.subscribe", "ApplicationService.SubscribeEvents", "request", "renderer-to-host", "progress-subscription-request", "progressSubscriptionRequest"),
        new("progress.subscribe", "ApplicationService.SubscribeEvents", "event", "host-to-renderer", "progress-event", "progressEvent"),
        new("application.cancel", "DesktopHost.TransportCancellation", "request", "renderer-to-host", "cancel-request", "cancelRequest"),
        new("application.cancel", "DesktopHost.TransportCancellation", "response", "host-to-renderer", "cancel-response", "cancelResponse"),
        new("application.resync-required", "DesktopHost.ResyncProjection", "event", "host-to-renderer", "resync-required-event", "resyncEvent"),
    ];
}

public interface IGeneratedRendererApplicationClient
{
    Task<GetApplicationBootstrapResponse> GetApplicationBootstrapAsync(GetApplicationBootstrapRequest request, CancellationToken cancellationToken);
    Task<ListResultItemsResponse> ListResultItemsAsync(ListResultItemsRequest request, CancellationToken cancellationToken);
    Task<GetResultDetailResponse> GetResultDetailAsync(GetResultDetailRequest request, CancellationToken cancellationToken);
    Task<GetProgressResponse> GetProgressAsync(GetProgressRequest request, CancellationToken cancellationToken);
    IAsyncEnumerable<ApplicationEvent> SubscribeEventsAsync(SubscribeEventsRequest request, CancellationToken cancellationToken);
}

public interface IGeneratedRendererProjectionCodec
{
    JsonElement Project(GetApplicationBootstrapRequest request, GetApplicationBootstrapResponse response);
    JsonElement Project(ListResultItemsRequest request, ListResultItemsResponse response);
    JsonElement Project(GetResultDetailRequest request, GetResultDetailResponse response);
    JsonElement Project(GetProgressRequest request, GetProgressResponse response);
    JsonElement Project(SubscribeEventsRequest request, ApplicationEvent applicationEvent);
}

public sealed class GeneratedRendererProjectionAdapter(IGeneratedRendererProjectionCodec codec)
{
    public JsonElement Project(string operation, object request, object response) => (operation, request, response) switch
    {
        ("application.bootstrap", GetApplicationBootstrapRequest typedRequest, GetApplicationBootstrapResponse typedResponse) => codec.Project(typedRequest, typedResponse),
        ("results.list", ListResultItemsRequest typedRequest, ListResultItemsResponse typedResponse) => codec.Project(typedRequest, typedResponse),
        ("results.detail", GetResultDetailRequest typedRequest, GetResultDetailResponse typedResponse) => codec.Project(typedRequest, typedResponse),
        ("progress.read", GetProgressRequest typedRequest, GetProgressResponse typedResponse) => codec.Project(typedRequest, typedResponse),
        _ => throw new InvalidDataException("The native projection is not registered for this renderer operation."),
    };

    public JsonElement ProjectEvent(string operation, object request, object applicationEvent) => (operation, request, applicationEvent) switch
    {
        ("progress.subscribe", SubscribeEventsRequest typedRequest, ApplicationEvent typedEvent) => codec.Project(typedRequest, typedEvent),
        _ => throw new InvalidDataException("The native event is not registered for this renderer operation."),
    };
}

public interface IGeneratedRendererRequestHandler
{
    Task<JsonElement?> TransportSessionEstablishAsync(RendererEnvelope envelope, JsonElement payload, CancellationToken cancellationToken);
    Task<JsonElement?> ApplicationBootstrapAsync(RendererEnvelope envelope, JsonElement payload, CancellationToken cancellationToken);
    Task<JsonElement?> ResultsListAsync(RendererEnvelope envelope, JsonElement payload, CancellationToken cancellationToken);
    Task<JsonElement?> ResultsDetailAsync(RendererEnvelope envelope, JsonElement payload, CancellationToken cancellationToken);
    Task<JsonElement?> ProgressReadAsync(RendererEnvelope envelope, JsonElement payload, CancellationToken cancellationToken);
    Task<JsonElement?> ProgressSubscribeAsync(RendererEnvelope envelope, JsonElement payload, CancellationToken cancellationToken);
    Task<JsonElement?> ApplicationCancelAsync(RendererEnvelope envelope, JsonElement payload, CancellationToken cancellationToken);
}

public static class GeneratedRendererRequestDispatcher
{
    public static Task<JsonElement?> DispatchAsync(IGeneratedRendererRequestHandler handler, RendererEnvelope envelope, JsonElement payload, CancellationToken cancellationToken)
        => envelope.Operation switch
        {
        "transport.session.establish" => handler.TransportSessionEstablishAsync(envelope, payload, cancellationToken),
        "application.bootstrap" => handler.ApplicationBootstrapAsync(envelope, payload, cancellationToken),
        "results.list" => handler.ResultsListAsync(envelope, payload, cancellationToken),
        "results.detail" => handler.ResultsDetailAsync(envelope, payload, cancellationToken),
        "progress.read" => handler.ProgressReadAsync(envelope, payload, cancellationToken),
        "progress.subscribe" => handler.ProgressSubscribeAsync(envelope, payload, cancellationToken),
        "application.cancel" => handler.ApplicationCancelAsync(envelope, payload, cancellationToken),
            _ => throw new InvalidDataException("The renderer request has no generated desktop adapter."),
        };
}

public interface IGeneratedRendererHostControl
{
    Task<RendererHostControlReceipt> CancelTransportAsync(RendererCancellationRequest request, CancellationToken cancellationToken);
    Task<RendererHostControlReceipt> ResyncProjectionAsync(RendererResyncRequest request, CancellationToken cancellationToken);
}

public sealed record RendererCancellationRequest(string TargetRequestId);
public sealed record RendererResyncRequest(string SubscriptionId, string CurrentProjectionVersion);
public sealed record RendererHostControlReceipt(string Outcome, string? CurrentProjectionVersion);
