<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\Infinium.Application\Infinium.Application.csproj" />
    <ProjectReference Include="..\..\src\Infinium.Domain\Infinium.Domain.csproj" />
    <ProjectReference Include="..\..\src\Infinium.Mo2\Infinium.Mo2.csproj" />
    <ProjectReference Include="..\..\src\Infinium.Persistence\Infinium.Persistence.csproj" />
  </ItemGroup>
</Project>
