<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\Infinium.Application\Infinium.Application.csproj" />
    <ProjectReference Include="..\..\src\Infinium.Bethesda\Infinium.Bethesda.csproj" />
    <ProjectReference Include="..\..\src\Infinium.Mo2\Infinium.Mo2.csproj" />
    <ProjectReference Include="..\..\src\Infinium.Domain\Infinium.Domain.csproj" />
    <ProjectReference Include="..\..\fixtures\tooling\Infinium.PublicFixtures\Infinium.PublicFixtures.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\..\contracts\repository\*.schema.json">
      <LogicalName>Infinium.Contracts.JsonSchema.%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
