<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\Infinium.Application\Infinium.Application.csproj" />
    <ProjectReference Include="..\..\src\Infinium.Coordinator\Infinium.Coordinator.csproj" />
    <ProjectReference Include="..\..\src\Infinium.Persistence\Infinium.Persistence.csproj" />
  </ItemGroup>
</Project>
