<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <FileVersion>2.5.2.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Infinium.Bethesda\Infinium.Bethesda.csproj" />
    <ProjectReference Include="..\..\src\Infinium.Mo2\Infinium.Mo2.csproj" />
    <ProjectReference Include="..\..\src\Infinium.Application\Infinium.Application.csproj" />
    <ProjectReference Include="..\..\src\Infinium.Coordinator\Infinium.Coordinator.csproj" />
    <ProjectReference Include="..\..\src\Infinium.Persistence\Infinium.Persistence.csproj" />
    <ProjectReference Include="..\..\fixtures\tooling\Infinium.PublicFixtures\Infinium.PublicFixtures.csproj" />
    <ProjectReference Include="..\Infinium.UnitTests\Infinium.UnitTests.csproj" />
  </ItemGroup>
  <Target Name="CopyManagedWorkerRuntime" AfterTargets="Build">
    <ItemGroup>
      <ManagedWorkerRuntimeFile Include="..\..\src\Infinium.Worker\bin\$(Configuration)\$(TargetFramework)\**\*"
                                Exclude="..\..\src\Infinium.Worker\bin\$(Configuration)\$(TargetFramework)\*.pdb" />
    </ItemGroup>
    <Copy SourceFiles="@(ManagedWorkerRuntimeFile)"
          DestinationFiles="@(ManagedWorkerRuntimeFile->'$(OutDir)%(RecursiveDir)%(Filename)%(Extension)')" />
  </Target>
  <Target Name="CopyCredentialHelperRuntime" AfterTargets="Build">
    <ItemGroup>
      <CredentialHelperRuntimeFile Include="..\..\src\Infinium.CredentialHelper\bin\$(Configuration)\$(TargetFramework)\**\*"
                                   Exclude="..\..\src\Infinium.CredentialHelper\bin\$(Configuration)\$(TargetFramework)\*.pdb" />
    </ItemGroup>
    <Copy SourceFiles="@(CredentialHelperRuntimeFile)"
          DestinationFiles="@(CredentialHelperRuntimeFile->'$(OutDir)CredentialHelper\%(RecursiveDir)%(Filename)%(Extension)')" />
  </Target>
</Project>
