<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Infinium.Domain\Infinium.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\..\contracts\json-schema\*.json">
      <LogicalName>Infinium.Contracts.JsonSchema.%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
