<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Infinium.EvaluatorV2</AssemblyName>
    <RootNamespace>Infinium.EvaluatorV2</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Infinium.Application\Infinium.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\..\..\contracts\json-schema\*.json">
      <LogicalName>Infinium.Contracts.JsonSchema.%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="protocol\*.schema.json">
      <LogicalName>Infinium.Contracts.JsonSchema.%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
    <Content Include="protocol\protocol.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="protocol\*.schema.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
