<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\Infinium.Application\Infinium.Application.csproj" />
    <ProjectReference Include="..\..\src\Infinium.Coordinator\Infinium.Coordinator.csproj" />
    <ProjectReference Include="..\..\src\Infinium.CredentialHelper\Infinium.CredentialHelper.csproj" />
    <ProjectReference Include="..\Infinium.UnitTests\Infinium.UnitTests.csproj" />
  </ItemGroup>
  <Target Name="CopyCredentialHelperRuntime" AfterTargets="Build">
    <ItemGroup>
      <CredentialHelperRuntimeFile Include="..\..\src\Infinium.CredentialHelper\bin\$(Configuration)\$(TargetFramework)\**\*"
                                   Exclude="..\..\src\Infinium.CredentialHelper\bin\$(Configuration)\$(TargetFramework)\*.pdb" />
    </ItemGroup>
    <Copy SourceFiles="@(CredentialHelperRuntimeFile)"
          DestinationFiles="@(CredentialHelperRuntimeFile->'$(OutDir)CredentialHelper\%(RecursiveDir)%(Filename)%(Extension)')" />
  </Target>
</Project>
