// <auto-generated />
namespace Infinium.DesktopHost;

internal static class DesktopAssetCatalog
{
    internal const string ManifestSha256 = "55f81bac65df0eb6f224c1b9c12bef3618f6a28e757073a36ce669d1ba52da71";
    internal const string RendererRegistryVersion = "1.3.0";
}
