<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Infinium.PublicFixtures</AssemblyName>
    <RootNamespace>Infinium.PublicFixtures</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Infinium.Application\Infinium.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\..\..\contracts\json-schema\*.json">
      <LogicalName>Infinium.Contracts.JsonSchema.%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
